CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_car START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_space START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_event START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE car (
  id BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_car) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_car,
  name VARCHAR(64),
  phone VARCHAR(64),
  plate VARCHAR(64)
);

ALTER TABLE PUBLIC.car ADD CONSTRAINT PUBLIC.PK_car PRIMARY KEY(ID);

CREATE TABLE space (
  id BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_space) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_space,
  number VARCHAR(64)
);

ALTER TABLE PUBLIC.space ADD CONSTRAINT PUBLIC.PK_space PRIMARY KEY(ID);

CREATE TABLE event (
  id BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_event) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_event,
  beg_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP,
  car_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL,
  cost DECIMAL(16,2)
);

ALTER TABLE PUBLIC.event ADD CONSTRAINT PUBLIC.event PRIMARY KEY(ID);
ALTER TABLE PUBLIC.event ADD CONSTRAINT PUBLIC.uq_event UNIQUE(beg_date,car_id,space_id);
ALTER TABLE event ADD CONSTRAINT fk_event_car_id foreign key (car_id) references car (id);
ALTER TABLE event ADD CONSTRAINT fk_event_space_id foreign key (space_id) references space (id);

