spring:
  datasource:
    url: jdbc:h2:mem:parking
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration/schema, classpath:/db/migration/data/dev